### ISSUE TITLE
Event messages sometimes corrupt

### ISSUE THREAD

**Issue by mattjohnsonpint** [archdx/zerolog-sentry#20]
I'm using `WithBreadcrumbs` to capture breadcrumbs that occur before errors.  In some cases, I've notice corruption in the event messages reported to Sentry.  Here's an example:

![image](https://github.com/archdx/zerolog-sentry/assets/1396388/3ecd1fa7-d1f7-4c3e-ae39-fc67b6f489e2)

There are two breadcrumbs following the error.  The first one is corrupt, the second one isn't.

I can't figure out how to reproduce it for you, but I started digging through the code based on the symptoms.  Since the corruption appears to only occur in the field values (not the field names), and the message text, I think it may be related to this part of the code:

https://github.com/archdx/zerolog-sentry/blob/dd4d17fcae3fedcf0dd6f85864aae50f32036039/writer.go#L150-L161

Everywhere that I'm seeing corruption is related to a call to `bytesToStrUnsafe`.  Perhaps there's some unsafe pointer issue there.  Can you investigate please?

Thanks.

**Comment by archdx** [comment]
Thank you, yeah, it could be the reason
We checked CaptureEvent that it does not use our buffer asyncronously after method returns. But linking breadcrumbs to the hub is a different story

Can you please try 1.8.4 version

**Comment by mattjohnsonpint** [comment]
Hi.  Can you please retag `1.8.4` as `v1.8.4` so Go will use it?  Thanks.
https://github.com/archdx/zerolog-sentry/tags
![image](https://github.com/user-attachments/assets/195decd6-5413-4d8f-b91f-edcadf38f999)

**Comment by mattjohnsonpint** [comment]
In the meantime, I imported it by git hash to try it out.  So far, so good.  No corruption.

**Comment by archdx** [comment]
Ah, released as v1.8.4

**Comment by mattjohnsonpint** [comment]
No corrupted messages since updating.  Thanks!
