### ISSUE TITLE
Pass zerolog `Fields` as Sentry event additional data

### ISSUE THREAD

**Issue by partizaans** [archdx/zerolog-sentry#3]
Hi!

There is a helper function called [`Fields`](https://pkg.go.dev/github.com/rs/zerolog#Event.Fields) in the zerolog library that helps to enrich the log information while keeping the error message unique. 
On the other side, the sentry accepts a map as the additional data of an event. 

As far as I checked, the extra fields other than `zerolog.MessageFieldName` and `zerolog.ErrorFieldName` are ignored. We can set those fields as the keys of `Extra` property of the sentry event. 
I'll try the PR, any suggestion is appreciated!

Thanks

**Comment by archdx** [comment]
Hi, merged your PR
We can consider adding Option to whitelist extra fields if we don't want to see them all in Sentry
It can be done later i guess
